Issue - 1 - User can search characters
addy-abid/guess-that-rick pull request #2
Opened 2021-11-10 18:42 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/141173816-ebf05216-66d3-4fdd-8cd3-62050f2b734a.mp4

2021-11-10 18:46 UTC, codingcodymiller requested changes

2021-11-10 18:46 UTC, codingcodymiller commented on js/main.js
> +  };
Instead of making this a global variable, you should just pass it as an argument to the `renderChars` function.

2021-11-10 18:46 UTC, codingcodymiller commented on js/main.js
> +// }
Please remove commented code prior to submitting for review

2021-11-10 19:07 UTC, codingcodymiller requested changes

2021-11-10 19:07 UTC, codingcodymiller commented on js/main.js
> +  var name = characterSearched.searched;
You can just remove this variable entirely, and just pass `$input.input.value` as an argument to `renderChars`.

2021-11-11 19:25 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/141356768-b853cf21-4096-4f99-848e-36621a66945b.mp4

2021-11-11 20:32 UTC, codingcodymiller approved these changes

2021-11-11 20:40 UTC, merged