Feature 2 - User can play random game
addy-abid/guess-that-rick pull request #4
Opened 2021-11-13 00:31 UTC by AddyAbid

https://user-images.githubusercontent.com/85080021/141598313-3c1c56b9-da17-4351-be15-e61495138e68.mp4

2021-11-13 00:50 UTC, AddyAbid commented
https://user-images.githubusercontent.com/85080021/141599178-b7a5f019-9857-4234-84ce-85ef0246b4dd.mp4

2021-11-15 18:07 UTC, AddyAbid commented
![Screen Shot 2021-11-15 at 10 07 18 AM](https://user-images.githubusercontent.com/85080021/141832312-e7d60f80-1164-410c-bc26-f5026fd93861.png)
![Screen Shot 2021-11-15 at 10 07 32 AM](https://user-images.githubusercontent.com/85080021/141832319-695595fd-6056-4508-824b-96cd70517645.png)

2021-11-15 18:10 UTC, codingcodymiller requested changes

2021-11-15 18:10 UTC, codingcodymiller commented on js/main.js
> +    }
Why is this function being defined _inside_ your `load` event handler?

2021-11-15 18:10 UTC, codingcodymiller commented on js/main.js
> +  }
Do you not have a function for switching views? 🤔

2021-11-15 18:10 UTC, codingcodymiller commented on js/main.js
> +  // $imgRow.appendChild($hiddenColumn);
Please remove commented code prior to submitting for review

2021-11-16 00:25 UTC, codingcodymiller approved these changes

2021-11-16 00:26 UTC, merged